### PR TITLE
Refactor and support anonymous functions

### PR DESCRIPTION
**Pull request by chrismccord**

### CODE REVIEW

**Review by lubien — APPROVED** [review]

**Review by jeregrine — APPROVED** [review]

**Comment by brainlid** [comment]
Thanks @chrismccord! And thanks @lubien and @jeregrine for reviewing it. Released as v0.2.1.

**Comment by fredwu** [comment]
Hi @chrismccord & co, it appears this change breaks `fly_postgres`:

```
function Fly.is_primary?/0 is undefined (module Fly is not available)
```

Any chance we get a new release of `fly_postgres` that works with this? 🙏

**Comment by brainlid** [comment]
Thanks @fredwu for reporting this issue! It's been fixed. 

- `fly_rpc` v0.3.0 was released to document the breaking changes
- `fly_postgres` v0.3.3 was released to use the new `fly_rpc`.

Please let me know if you have any more issues!

**Comment by fredwu** [comment]
Thanks @brainlid ! 🙏

**Pull request merged**
